### PR TITLE
QA Fixes to Sandbox

### PR DESCRIPTION
**Pull request by cbhernan**
### What does this PR do?
Updates recent updates from development into sandbox

Fixes:

- Update angeleno site urls to new sandbox urls
- Allow text to be highlighted in MFA TOTP modal
- Update copyright date
- Fixed unable to disable immediately after enabling https://github.com/CityOfLosAngeles/angeleno-my-account/issues/123
- Fixed scrollbar over text inputs and edit button on Profile page
- Fixed error showing prior to user interaction. Disabled continue option until fields have values.

### CODE REVIEW

**Comment by technima** [comment]
@cbhernan Can you update the app to use the new custom domain for the auth0 sandbox tenant?

**Comment by technima** [comment]
@cbhernan please remove the copyright notice ni the footer

**Comment by technima** [comment]
@cbhernan please hide the connected services section since the consent management module is on hold.

**Comment by cbhernan** [comment]
@technima Changes have been made and are reflected in the preview url

**Review by nickchaula — APPROVED** [review]
LGTM

**Pull request merged**
